### PR TITLE
Joey

### PR DESCRIPTION
**Pull request by Doglikergaming**

### CODE REVIEW

**Review by Hempflingclub — COMMENTED** [review]
Inefficient Changes in GUI.java
The Comment in Line 3 will kill Performance

**Comment by Doglikergaming** [comment]
> Inefficient Changes in GUI.java The Comment in Line 3 will kill Performance

I refuse to agree. Begone, abomination

**Comment by Hempflingclub** [comment]
> > Inefficient Changes in GUI.java The Comment in Line 3 will kill Performance
> 
> I refuse to agree. Begone, abomination
ddvtmz1-cadfaa7f-6da9-4b59-a0fe-6ed5742af38c

**Comment by Doglikergaming** [comment]
> > > Inefficient Changes in GUI.java The Comment in Line 3 will kill Performance
> > 
> > 
> > I refuse to agree. Begone, abomination
> > ddvtmz1-cadfaa7f-6da9-4b59-a0fe-6ed5742af38c

:)

**Pull request closed without merging**
